services:
  backend:
    build: backend
    image: olivierdsm/backend:latest
    env_file:
      - .env
  frontend:
    build: 
      context: frontend
      args:
        MESSAGE: SALUT
    image: olivierdsm/frontend:latest
    env_file:
      - .env      
